### ISSUE TITLE
participate in it

### ISSUE THREAD

**Issue by huahuaLover** [felixlinker/tamarin-workshop#4]
how to participate in this workshop? i am interested in it!

**Comment by felixlinker** [comment]
Hi! Glad to see that you're interested. Unfortunately, I don't know when I will host this workshop again. But two further notes:

- I held this workshop one week ago at the IETF 118, and as part of that, it was recorded. You can find timestamps to the relevant parts of the recording [here](https://github.com/felixlinker/tamarin-workshop#recording). This might help you with solving the exercises on your own :)
- If you can think of any other occasion where you would like me to run the workshop, don't hesitate to reach out. You can find my contact details [here](https://felixlinker.de/contact/).

**Comment by huahuaLover** [comment]
I'm glad to receive your response, and fortunately, it's been recorded so I can watch it later. Currently, I am also studying Tamarin. However, when I use Tamarin to automatically prove a lemma, it doesn't terminate. Although I have resolved the issue of 'Partial deconstructions left,' for some lemmas, it still doesn't terminate. So, I plan to use custom proof heuristics. But even after studying the 'Using an Oracle' section in the manual, I still struggle to understand how to write an oracle. I would greatly appreciate any advice or recommended articles you could provide. Looking forward to your reply

**Comment by huahuaLover** [comment]
Thank you very much. If I expect you to host a workshop, I will get in touch with you！

**Comment by felixlinker** [comment]
There's no "right solution" to writing an oracle. I encourage you to watch my presentation from the IETF because in the second part, I go into the basic reasoning underlying manual proofs in Tamarin :) And writing an oracle is just an assisted way to prove a lemma manually.

If you have more, specific questions, I'd encourage you to post them to Tamarin's Google group. It is quite active!

**Comment by huahuaLover** [comment]
Thank you for your response.I am watching your presentation from the IETF :) As you mentioned, "writing an oracle is just an assisted way to prove a lemma manually," it means that we have manually proven the lemma first and then written the oracle. When we run it again, we use the pre-written oracle. Does it mean that the oracle is written based on our knowledge of how to prove a lemma?

**Comment by huahuaLover** [comment]
Thank you very much! I will post the specific questions to Tamarin's Google group.Thanks again!

**Comment by felixlinker** [comment]
> As you mentioned, "writing an oracle is just an assisted way to prove a lemma manually," it means that we have manually proven the lemma first and then written the oracle.

No.

> Does it mean that the oracle is written based on our knowledge of how to prove a lemma?

Yes! You don't need to prove the lemma completely first when writing an oracle. Partial proofs are fine. I always use an oracle of this form in my proofs: https://github.com/adem-wg/adem-proofs/blob/main/oracle.py (From a different project of mine.)

Documentation is not existent, but I think you can see what I'm going for :) I have a priority list of goals that I want to solve and I always solve the goal that matches the highest rank matcher.

**Comment by huahuaLover** [comment]
Thank you for your response.How did you get priority list of goals? Are there any tricks or common practices，i have no idea to get priority list of goals.I am currently studying the proof about 5GAKA, but I don't know how they got the priority list of goals. I have been confused about this for a long time.I am looking forward to your reply

**Comment by huahuaLover** [comment]
I am very sorry to take so long of your time. I am very grateful to receive your reply. I will continue to learn tamarin in the future

**Comment by felixlinker** [comment]
There is no recipe to follow. As I said, I suggest watching my presentation at the IETF. Beyond that, it's something that you must learn. I would not suggest looking at big projects like 5GAKA. These model real-world systems and are enormously complex. It's often better to look at small examples and understand how their proofs work. These projects need not have an oracle! You must first learn why proofs in Tamarin terminate.

**Comment by huahuaLover** [comment]
I am grateful to receive your response. I am watching your presentation at the IETF and have been working on ex3. I learned a lot from your presentation, and I truly appreciate it. I hope you can talk more about Tamarin-prover in the future because I noticed there are very few videos related to Tamarin-prover. As you mentioned, I will go ahead and study smaller examples. I plan to learn from the examples provided in Tamarin-prover.Do you have any suggestions for learning examples? Thank you so much

**Comment by huahuaLover** [comment]
You always answer my questions sincerely and patiently. I am very grateful

**Comment by felixlinker** [comment]
Hey! I cannot think of any specific models to look at, sorry :) I hope my exercises help.

**Comment by huahuaLover** [comment]
Thanks a lot!
